# Generated by Django 5.0 on 2024-07-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletask',
            name='priority',
            field=models.CharField(choices=[('high', 'high'), ('moderate', 'moderate'), ('minor', 'minor')], default='moderate', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprinttask',
            name='priority',
            field=models.CharField(choices=[('high', 'high'), ('moderate', 'moderate'), ('minor', 'minor')], default='moderate', max_length=30),
            preserve_default=False,
        ),
    ]
