# Generated by Django 5.0 on 2024-07-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_simpletask_priority_sprinttask_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='started_at',
            field=models.DateTimeField(verbose_name='Start date'),
        ),
    ]
