# Generated by Django 5.0 on 2024-07-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_simpletask_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpletask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Should be finished by'),
        ),
    ]
