# Generated by Django 5.0 on 2024-07-12 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_simpletask_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpletask',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.category', verbose_name='Category'),
        ),
    ]
